# Generated by Django 4.2.13 on 2026-09-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_report_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('prescription', 'Prescription'), ('report', 'Report / Lab Result'), ('imaging', 'Imaging / Scan'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='patient_uploads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='records.patient')),
            ],
        ),
    ]
